### PR TITLE
Adapt output for vcstool

### PR DESCRIPTION
**Pull request by paulbovbel**

### CODE REVIEW

**Comment by dirk-thomas** [comment]
`vcstool` can read the `.rosinstall` file format already. No need to customize the output. See https://github.com/dirk-thomas/vcstool#import-set-of-repositories

**Comment by dirk-thomas** [comment]
> Given a test, would you be amenable to adding this to rosinstall?

Sounds good to me. @wjwwood @sloretz might want to comment on this too since they are actually maintaining this package.

**Comment by sloretz** [comment]
An option to output in `vcstool`'s format sounds good to me as well.

**Comment by wjwwood** [comment]
Fine by me.

**Pull request closed without merging**
